sudo: true # required for docker

services:
  - docker

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - ./tools/composer.sh install

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose-test.yml up -d
  - echo "wait for mysql is up: "
  - until ./tools/mysql-is-up.sh; do printf .; sleep 1; done;

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - docker-compose -f docker-compose.yml -f docker-compose-test.yml down

after_success:
  # Coverage reporting
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
